/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Forms;

import Classes.ClasseCidade;
import Classes.ClasseCliente;
import Classes.model.Cidades;
import Classes.model.Clientes;
import Classes.model.Utilitarios;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 892101
 */
public class CadCliente extends javax.swing.JDialog {
 
    public void listarClientes() {

        ClasseCliente dao = new ClasseCliente();
        
        List<Clientes> lista = dao.listarClientesBusca();
        DefaultTableModel dados = (DefaultTableModel) tabelaClientes.getModel();
        dados.setNumRows(0);

        for (Clientes c : lista) {
            dados.addRow(new Object[]{
             c.getId(),
             c.getTipoPessoa(),
             c.getNome(),         
             c.getRg(),
             c.getCpf(),
             c.getCnpj(),
             c.getDataNasc(),
             c.getCelular(),
             c.getCep(),
             c.getEndereco(),
             c.getBairro(),
             c.getCidade(),      
             c.getEstado()
              
             
            });
    
        }

    }
    
    public void listarClientesPorNome(String nome) {

        ClasseCliente dao = new ClasseCliente();
        
        List<Clientes> lista = dao.buscarPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaClientes.getModel();
        dados.setNumRows(0);

        for (Clientes c : lista) {
            dados.addRow(new Object[]{
             c.getId(),
             c.getTipoPessoa(),
             c.getNome(),         
             c.getRg(),
             c.getCpf(),
             c.getCnpj(),
             c.getDataNasc(),
             c.getCelular(),
             c.getCep(),
             c.getEndereco(),
             c.getBairro(),
             c.getCidade(),      
             c.getEstado(),
              
             
            });
    
        }

    }
     public void listarClientesPorCPF(String Cpf) {

        ClasseCliente dao = new ClasseCliente();
        
        List<Clientes> lista = dao.buscarPorCpf(Cpf);
        DefaultTableModel dados = (DefaultTableModel) tabelaClientes.getModel();
        dados.setNumRows(0);

        for (Clientes c : lista) {
            dados.addRow(new Object[]{
             c.getId(),
             c.getTipoPessoa(),
             c.getNome(),         
             c.getRg(),
             c.getCpf(),
             c.getCnpj(),
             c.getDataNasc(),
             c.getCelular(),
             c.getCep(),
             c.getEndereco(),
             c.getBairro(),
             c.getCidade(),      
             c.getEstado(),
              
             
            });
    
        }

    }

    public CadCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listarClientes();
        tema();
        desabilitarCampos();
        txtpesquisa.requestFocus();
        
        btnCancelar.setEnabled(false);
        btnnovo.setEnabled(true);
        btnsalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnEditar.setEnabled(false);
        this.toFront();
        
    }
     public CadCliente() {
        
        initComponents();
        listarClientes();
        tema();
        desabilitarCampos();
        txtpesquisa.requestFocus();
        
        btnCancelar.setEnabled(false);
        btnnovo.setEnabled(true);
        btnsalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnEditar.setEnabled(false);
        this.toFront();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        txtpesquisa = new javax.swing.JTextField();
        btnpesquisar = new javax.swing.JButton();
        cbTpPesquisa = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        painel_dados5 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        txtcpf = new javax.swing.JFormattedTextField();
        jLabel67 = new javax.swing.JLabel();
        txtcel = new javax.swing.JFormattedTextField();
        LabelCpf = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        txtrg = new javax.swing.JFormattedTextField();
        jLabel71 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtend = new javax.swing.JTextField();
        txtbairro = new javax.swing.JFormattedTextField();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        txtcep = new javax.swing.JFormattedTextField();
        jLabel78 = new javax.swing.JLabel();
        cbuf = new javax.swing.JComboBox<>();
        jLabel79 = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JFormattedTextField();
        LabelCnpj = new javax.swing.JLabel();
        cbCidade = new javax.swing.JComboBox<>();
        jLabel82 = new javax.swing.JLabel();
        cbTipoPessoa = new javax.swing.JComboBox<>();
        txtdatanasc = new javax.swing.JFormattedTextField();
        jLabel77 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JToggleButton();
        btnok = new javax.swing.JButton();
        btnnovo = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tabelaClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TIPO PESSOA", "NOME", "RG", "CPF", "CNPJ", "DATA DE NASCIMENTO", "CELULAR", "CEP", "ENDEREÇO", "BAIRRO", "CIDADE", "UF"
            }
        ));
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaClientes);

        txtpesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisaActionPerformed(evt);
            }
        });
        txtpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisaKeyPressed(evt);
            }
        });

        btnpesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnpesquisar.setText("Pesquisar");
        btnpesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpesquisarMouseClicked(evt);
            }
        });
        btnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisarActionPerformed(evt);
            }
        });

        cbTpPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione ", "Código", "Nome", "Cpf", "Cnpj", "Física", "Jurídica", " " }));
        cbTpPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTpPesquisaActionPerformed(evt);
            }
        });

        jLabel1.setText("Conusta por:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbTpPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnpesquisar))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTpPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        jTabbedPane5.addTab("Consulta de clientes", jPanel4);

        painel_dados5.setBackground(new java.awt.Color(255, 255, 255));
        painel_dados5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel66.setText("Nome:");

        try {
            txtcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcpf.setEnabled(false);
        txtcpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfActionPerformed(evt);
            }
        });

        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        try {
            txtcel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelCpf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelCpf.setText("CPF:");

        jLabel69.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel69.setText("RG:");

        try {
            txtrg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtrg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrgActionPerformed(evt);
            }
        });

        jLabel71.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel71.setText("Celular:");

        txtnome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });

        txtend.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtbairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel73.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel73.setText("CEP:");

        jLabel74.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel74.setText("Endereço:");

        jLabel76.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel76.setText("Bairro:");

        try {
            txtcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcepActionPerformed(evt);
            }
        });
        txtcep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcepKeyPressed(evt);
            }
        });

        jLabel78.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel78.setText("UF:");

        cbuf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbuf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbuf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbufItemStateChanged(evt);
            }
        });
        cbuf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbufActionPerformed(evt);
            }
        });

        jLabel79.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel79.setText("Cidade:");

        try {
            txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpj.setToolTipText("");
        txtCnpj.setEnabled(false);
        txtCnpj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        LabelCnpj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelCnpj.setText("CNPJ:");
        LabelCnpj.setEnabled(false);

        cbCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        jLabel82.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel82.setText("Tipo Pessoa:");

        cbTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Física", "Jurídica" }));
        cbTipoPessoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoPessoaItemStateChanged(evt);
            }
        });
        cbTipoPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoPessoaActionPerformed(evt);
            }
        });

        txtdatanasc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdatanasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatanascActionPerformed(evt);
            }
        });

        jLabel77.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel77.setText("Data Nascimento:");

        txtCodigo.setEnabled(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnok.setText("OK");
        btnok.setEnabled(false);
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_dados5Layout = new javax.swing.GroupLayout(painel_dados5);
        painel_dados5.setLayout(painel_dados5Layout);
        painel_dados5Layout.setHorizontalGroup(
            painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_dados5Layout.createSequentialGroup()
                .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painel_dados5Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel67)
                        .addGap(333, 333, 333)
                        .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_dados5Layout.createSequentialGroup()
                                .addComponent(jLabel71)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel_dados5Layout.createSequentialGroup()
                                .addComponent(jLabel82)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painel_dados5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painel_dados5Layout.createSequentialGroup()
                                .addComponent(jLabel74)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtend, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel_dados5Layout.createSequentialGroup()
                                .addComponent(jLabel66)
                                .addGap(9, 9, 9)
                                .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel73)
                            .addGroup(painel_dados5Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(9, 9, 9)
                .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_dados5Layout.createSequentialGroup()
                        .addComponent(jLabel78)
                        .addGap(10, 10, 10)
                        .addComponent(cbuf, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_dados5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel77)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdatanasc, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_dados5Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_dados5Layout.createSequentialGroup()
                        .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_dados5Layout.createSequentialGroup()
                                .addComponent(jLabel69)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtrg, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel_dados5Layout.createSequentialGroup()
                                .addComponent(jLabel76)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_dados5Layout.createSequentialGroup()
                                .addComponent(jLabel79)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel_dados5Layout.createSequentialGroup()
                                .addComponent(LabelCpf)
                                .addGap(10, 10, 10)
                                .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LabelCnpj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(331, 331, 331))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_dados5Layout.createSequentialGroup()
                        .addComponent(btnok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addGap(16, 16, 16))))
        );
        painel_dados5Layout.setVerticalGroup(
            painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_dados5Layout.createSequentialGroup()
                .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_dados5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdatanasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel77))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_dados5Layout.createSequentialGroup()
                        .addContainerGap(30, Short.MAX_VALUE)
                        .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel82)
                                .addComponent(cbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel67)
                                .addComponent(txtcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel71))
                            .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painel_dados5Layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(jLabel66))
                                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel74)
                                .addComponent(txtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel73)))
                        .addGap(5, 5, 5)))
                .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painel_dados5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel78)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel76))
                    .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel79)
                        .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel69))
                    .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelCnpj)
                        .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_dados5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(LabelCpf)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(painel_dados5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnok))
                .addContainerGap())
        );

        jTabbedPane5.addTab("Dados Pessoais", painel_dados5);

        btnnovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnnovo.setText("+ Novo");
        btnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovoActionPerformed(evt);
            }
        });

        btnsalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsalvar.setText("Salvar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(btnnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseClicked
        //Pega os dados
        

    }//GEN-LAST:event_tabelaClientesMouseClicked

    private void txtpesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaKeyPressed
       
    }//GEN-LAST:event_txtpesquisaKeyPressed

    private void btnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisarActionPerformed

        
     
        String tipoPesquisa = (String) cbTpPesquisa.getSelectedItem();
        
            if("Selecione".equals(tipoPesquisa) || txtpesquisa.equals(" ")){
                listarClientes(); 
                
            }else if ("Código".equals(tipoPesquisa)){
                
            }else if ("Nome".equals(tipoPesquisa)){
                String nome = "%" + txtpesquisa.getText() + "%";
                listarClientesPorNome(nome);
                
            }else if("Cpf".equals(tipoPesquisa)){
                String Cpf = "%" + txtpesquisa.getText() + "%";
                listarClientesPorCPF(Cpf);
                
            }else if("Cnpj".equals(tipoPesquisa)){
                String Cnpj = "%" + txtpesquisa.getText() + "%";
            }
            
        
        
        
        
        
        
        /*if(txtpesquisa.equals("")){
            listarClientes();
        } else {
            listarClientesPorNome(pesquisa);
            System.out.println("Pronto");
        }  */
          

    }//GEN-LAST:event_btnpesquisarActionPerformed
    //
    private void btnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovoActionPerformed
        new Utilitarios().LimpaTela(painel_dados5);
        btnCancelar.setVisible(true);
        habilitarCampos();
        btnsalvar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnnovo.setEnabled(false);
        btnExcluir.setEnabled(false);
        jTabbedPane5.setSelectedComponent(painel_dados5);
        jTabbedPane5.setEnabledAt(0, false);
         btnCancelar.setEnabled(true);
    }//GEN-LAST:event_btnnovoActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // boto salvar
            Clientes obj = new Clientes();
            obj.setTipoPessoa((String)cbTipoPessoa.getSelectedItem());
            obj.setNome(txtnome.getText());
            obj.setRg(txtrg.getText());
            obj.setCpf(txtcpf.getText());
            obj.setCnpj(txtCnpj.getText());
            obj.setDataNasc(txtdatanasc.getText());
            obj.setEndereco(txtend.getText());
            obj.setBairro(txtbairro.getText());
            obj.setCidade((String)cbCidade.getSelectedItem());
            obj.setCep(Integer.parseInt(txtcep.getText()));
            obj.setEstado((String)cbuf.getSelectedItem());
            obj.setCelular(txtcel.getText());

            ClasseCliente dao = new ClasseCliente();

        try {
            dao.cadastrarCliente(obj);
            listarClientes();
             btnCancelar.setEnabled(false);
              btnsalvar.setEnabled(true);
              btnEditar.setEnabled(false);
                btnnovo.setEnabled(false);
                 btnExcluir.setEnabled(false);
                limpaCampos();
                desabilitarCampos();
            
             jTabbedPane5.setEnabledAt(0, true);

        } catch (SQLException ex) {
            Logger.getLogger(CadCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

            new Utilitarios().LimpaTela(painel_dados5);

    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        habilitarCampos();
        btnCancelar.setEnabled(true);
        btnok.setEnabled(true);
        jTabbedPane5.setEnabledAt(0, false);

        
    
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
         int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o cadastro?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){

          
                Clientes obj = new Clientes();
                int selectedRow = tabelaClientes.getSelectedRow();
                obj.setId(Integer.parseInt(tabelaClientes.getValueAt(selectedRow, 0).toString()));

                ClasseCliente objc = new ClasseCliente();
                objc.excluirCliente(obj);
            
            btnExcluir.setEnabled(false);
            limpaCampos();
            desabilitarCampos();
            listarClientes();
           // panel_abas.setEnabledAt(0, true);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnpesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpesquisarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpesquisarMouseClicked

    private void txtpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesquisaActionPerformed

    private void cbTpPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTpPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTpPesquisaActionPerformed

    private void tabelaClientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseReleased
       tabelaClientes.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
           @Override
           
         
           public void valueChanged(ListSelectionEvent e) {
                 if (!e.getValueIsAdjusting() && tabelaClientes.getSelectedRow() != -1) {
             
               int selectedRow = tabelaClientes.getSelectedRow();
                txtCodigo.setText(tabelaClientes.getValueAt(selectedRow, 0).toString());
                cbTipoPessoa.setSelectedItem((String) tabelaClientes.getValueAt(selectedRow, 1).toString());
                txtnome.setText(tabelaClientes.getValueAt(selectedRow, 2).toString());
                txtrg.setText(tabelaClientes.getValueAt(selectedRow, 3).toString());
                txtcpf.setText(tabelaClientes.getValueAt(selectedRow, 4).toString());
                txtCnpj.setText( tabelaClientes.getValueAt(selectedRow, 5).toString());  
                txtdatanasc.setText( tabelaClientes.getValueAt(selectedRow, 6).toString());
                txtcel.setText(tabelaClientes.getValueAt(selectedRow, 7).toString());
                txtcep.setText(tabelaClientes.getValueAt(selectedRow, 8).toString());
                txtend.setText(tabelaClientes.getValueAt(selectedRow, 9).toString());
                txtbairro.setText(tabelaClientes.getValueAt(selectedRow, 10).toString());
                cbCidade.setSelectedItem(tabelaClientes.getValueAt(selectedRow, 11).toString());
                cbuf.setSelectedItem(tabelaClientes.getValueAt(selectedRow, 12).toString());
                jTabbedPane5.setSelectedComponent(painel_dados5);
                btnEditar.setEnabled(true);
                btnExcluir.setEnabled(true);
                btnCancelar.setEnabled(false);
           }
           
           }
       
    
    });
    }//GEN-LAST:event_tabelaClientesMouseReleased

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpaCampos();
        listarClientes();
        btnCancelar.setEnabled(false);
        btnsalvar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnnovo.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnok.setEnabled(false);
        desabilitarCampos();
        
         jTabbedPane5.setEnabledAt(0, true);

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtdatanascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatanascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatanascActionPerformed

    private void cbTipoPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoPessoaActionPerformed
        
    }//GEN-LAST:event_cbTipoPessoaActionPerformed

    private void cbufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbufActionPerformed

    private void cbufItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbufItemStateChanged
        // TODO add your handling code here:
        listarCidades();
    }//GEN-LAST:event_cbufItemStateChanged

    private void txtcepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcepKeyPressed

    }//GEN-LAST:event_txtcepKeyPressed

    private void txtcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcepActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrgActionPerformed

    private void txtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
            alterarCliente();
            listarClientes();
            btnok.setEnabled(false);
            desabilitarCampos();
             btnCancelar.setEnabled(false);
             btnnovo.setEnabled(true);
             btnsalvar.setEnabled(false);
             btnExcluir.setEnabled(false);
             btnEditar.setEnabled(false);
             jTabbedPane5.setEnabledAt(0, true);


// TODO add your handling code here:
    }//GEN-LAST:event_btnokActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void cbTipoPessoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoPessoaItemStateChanged
        String TipoPessoa = (String) cbTipoPessoa.getSelectedItem();

        if("Física".equals(TipoPessoa)){
            LabelCpf.setEnabled(true);
            txtcpf.setEnabled(true);
            LabelCnpj.setEnabled(false);
            txtCnpj.setEnabled(false);
            txtCnpj.setText("");
        }else{
            LabelCpf.setEnabled(false);
            txtcpf.setEnabled(false);
            txtcpf.setText("");
            LabelCnpj.setEnabled(true);
            txtCnpj.setEnabled(true);            

        }
    }//GEN-LAST:event_cbTipoPessoaItemStateChanged

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) throws ClassNotFoundException, InstantiationException {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCliente().setVisible(true);
            }
        
        */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCnpj;
    private javax.swing.JLabel LabelCpf;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnnovo;
    private javax.swing.JButton btnok;
    private javax.swing.JButton btnpesquisar;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JComboBox<String> cbCidade;
    private javax.swing.JComboBox<String> cbTipoPessoa;
    private javax.swing.JComboBox<String> cbTpPesquisa;
    private javax.swing.JComboBox<String> cbuf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JPanel painel_dados5;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtbairro;
    private javax.swing.JFormattedTextField txtcel;
    private javax.swing.JFormattedTextField txtcep;
    private javax.swing.JFormattedTextField txtcpf;
    private javax.swing.JFormattedTextField txtdatanasc;
    private javax.swing.JTextField txtend;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtpesquisa;
    private javax.swing.JFormattedTextField txtrg;
    // End of variables declaration//GEN-END:variables
        public final void tema(){
            
                try
                {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    SwingUtilities.updateComponentTreeUI(this);
                }
                    catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException erro)
                {
                    JOptionPane.showMessageDialog(null, erro);
                }
        }
        
        public void listarCidades(){
            ClasseCidade repositorio = new ClasseCidade();

             String estado = cbuf.getSelectedItem().toString();
             cbCidade.removeAllItems();
             List<Cidades> estados = repositorio.listarCidadesPorUF(estado);
             for (Cidades estado1 : estados) {
            
            cbCidade.addItem(estado1.getNome());

             }
        }
        public void desabilitarCampos(){

            txtCnpj.setEnabled(false);
            txtCodigo.setEnabled(false);
            txtbairro.setEnabled(false);
            txtcel.setEnabled(false);
            txtcep.setEnabled(false);
            txtcpf.setEnabled(false);
            txtdatanasc.setEnabled(false);
            txtend.setEnabled(false);
            txtnome.setEnabled(false);
            txtpesquisa.setEnabled(false);
            txtrg.setEnabled(false);
            cbCidade.setEnabled(false);
            cbTipoPessoa.setEnabled(false);
            cbuf.setEnabled(false);
            btnCancelar.setEnabled(false);
            
            
                    

    }
        public void habilitarCampos(){
            
           // txtCnpj.setEnabled(true);
            
            txtbairro.setEnabled(true);
            txtcel.setEnabled(true);
            txtcep.setEnabled(true);
            //txtcpf.setEnabled(true);
            txtdatanasc.setEnabled(true);
            txtend.setEnabled(true);
            txtnome.setEnabled(true);
            txtpesquisa.setEnabled(true);
            txtrg.setEnabled(true);
            cbCidade.setEnabled(true);
            cbTipoPessoa.setEnabled(true);
            cbuf.setEnabled(true);
           
        
        }
         public final void limpaCampos(){
            txtCnpj.setText("");
            txtCnpj.setText("");
            txtCodigo.setText("");
            txtbairro.setText("");
            txtcel.setText("");
            txtcep.setText("");
            txtcpf.setText("");
            txtdatanasc.setText("");
            txtend.setText("");
            txtnome.setText("");
            txtpesquisa.setText("");
            txtrg.setText("");
            cbCidade.setSelectedItem("Selecione");
            cbuf.setSelectedItem("AC");
            cbTipoPessoa.setSelectedItem("Física");
            
         } 
         public void alterarCliente(){

           Clientes obj = new Clientes();
            obj.setTipoPessoa((String)cbTipoPessoa.getSelectedItem());
            obj.setNome(txtnome.getText());
            obj.setRg(txtrg.getText());
            obj.setCpf(txtcpf.getText());
            obj.setCnpj(txtCnpj.getText());
            obj.setDataNasc(txtdatanasc.getText());
            obj.setEndereco(txtend.getText());
            obj.setBairro(txtbairro.getText());
            obj.setCidade((String)cbCidade.getSelectedItem());
            obj.setCep(Integer.parseInt(txtcep.getText()));
            obj.setEstado((String)cbuf.getSelectedItem());
            obj.setCelular(txtcel.getText());
            obj.setId(Integer.parseInt(txtCodigo.getText()));
            ClasseCliente dao = new ClasseCliente();

        try {
            dao.alterarCliente(obj);
        } catch (SQLException ex) {
            Logger.getLogger(CadCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

            new Utilitarios().LimpaTela(painel_dados5);

    }                                         
         
         
}     


    


