/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;


import Classes.ClasseLogin;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.*;
import javax.swing.border.Border;
import java.sql.SQLException;
/**
 *
 * @author rafae
 */
public class PLogin extends javax.swing.JFrame {

    /**
     * Creates new form PLogin
     */
    public PLogin() {
        initComponents();         
        setUndecorated(true);
        
        Border border = BorderFactory.createLineBorder(Color.DARK_GRAY, 1);
        this.getRootPane().setBorder(border);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lLogin = new javax.swing.JLabel();
        bEntrar1 = new javax.swing.JButton();
        bSair = new javax.swing.JButton();
        cUsuario = new javax.swing.JTextField();
        cSenha = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        lPassword = new javax.swing.JLabel();
        lUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lLogin.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        lLogin.setText("LOGIN");
        getContentPane().add(lLogin);
        lLogin.setBounds(150, 50, 95, 45);

        bEntrar1.setBackground(new java.awt.Color(102, 102, 102));
        bEntrar1.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        bEntrar1.setForeground(new java.awt.Color(102, 102, 102));
        bEntrar1.setText("ENTRAR");
        bEntrar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bEntrar1.setContentAreaFilled(false);
        bEntrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEntrar1.setDefaultCapable(false);
        bEntrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(bEntrar1);
        bEntrar1.setBounds(100, 240, 90, 31);

        bSair.setBackground(new java.awt.Color(153, 153, 153));
        bSair.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        bSair.setForeground(new java.awt.Color(102, 102, 102));
        bSair.setText("SAIR");
        bSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bSair.setContentAreaFilled(false);
        bSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSair.setDefaultCapable(false);
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });
        getContentPane().add(bSair);
        bSair.setBounds(210, 240, 60, 31);

        cUsuario.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        cUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(cUsuario);
        cUsuario.setBounds(100, 130, 180, 31);

        cSenha.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        cSenha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(cSenha);
        cSenha.setBounds(100, 180, 180, 32);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(385, 0, 17, 373);

        lPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconPASSWORD.png"))); // NOI18N
        getContentPane().add(lPassword);
        lPassword.setBounds(80, 180, 20, 30);

        lUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconUSER.png"))); // NOI18N
        getContentPane().add(lUser);
        lUser.setBounds(80, 130, 20, 30);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        jLabel1.setText("VINDO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 150, 130, 40);

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        jLabel2.setText("BEM ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 80, 90, 40);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundotesteSoftware.png"))); // NOI18N
        fundo.setText("jLabel1");
        getContentPane().add(fundo);
        fundo.setBounds(-20, -80, 660, 460);

        setSize(new java.awt.Dimension(615, 332));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        repaint();
    }//GEN-LAST:event_bSairActionPerformed

    private void bEntrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntrar1ActionPerformed
        // TODO add your handling code here:
        String usuario = cUsuario.getText();
        String senha = cSenha.getText();
        try {
            habilitarLogin(usuario, senha);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Falha no Login, Tente Novamente!\n\n" + ex);
        }
        
    }//GEN-LAST:event_bEntrar1ActionPerformed

    private void cSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PLogin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEntrar1;
    private javax.swing.JButton bSair;
    private javax.swing.JPasswordField cSenha;
    private javax.swing.JTextField cUsuario;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lUser;
    // End of variables declaration//GEN-END:variables

    
        public void habilitarLogin(String usuario, String senha) throws SQLException{
        
        ClasseLogin Login = new ClasseLogin();
        boolean validar = Login.validaLogin(usuario, senha);
        
        if(validar == true){
            this.setVisible(false);
            TInicial2 principal = new TInicial2();
            //principal.setUndecorated(true);
            //principal.getUsuario(usuario);
            
            principal.setVisible(true);
           
        }else{
            JOptionPane.showMessageDialog(null, "Usuario e/ou Senha incorretos");
        }
    }
        
        public final void tema(){

        try
        {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        }
            catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException erro)
        {
            JOptionPane.showMessageDialog(null, erro);
        }
    } 
}
